use_default_settings: true

server:
  secret_key: "randomstring123abc"
  limiter: false
  image_proxy: true
  bind_address: "0.0.0.0"
  port: 8080

search:
  formats:
    - html
    - json
  safe_search: 0

outgoing:
  request_timeout: 10.0
